##
## Makefile for blabla in /home/soumph_s/tmp
## 
## Made by sirininh soumpholphakdy
## Login   <soumph_s@epitech.net>
## 
## Started on  Mon Oct 20 08:44:20 2014 sirininh soumpholphakdy
## Last update Mon Oct 20 10:37:39 2014 sirininh soumpholphakdy
##

OBJ=	main.o my_putchar.o my_putstr.o

all:	teest

teest:	$(OBJ)
	cc -o teest $(OBJ)
