##
## Makefile for Makefile in /home/soumph_s
## 
## Made by sirininh soumpholphakdy
## Login   <soumph_s@epitech.net>
## 
## Started on  Thu Dec 18 16:17:58 2014 sirininh soumpholphakdy
## Last update Tue Apr  7 16:18:16 2015 sirininh soumpholphakdy
##

NAME	=	

SRCS	=

OBJS	=	

all:

$(NAME):

clean:

fclean:

re:
